name: IsometricCityHost
options:
  deploymentTarget:
    iOS: "26.0"
configs:
  Debug: debug
  Release: release
targets:
  IsometricCityHost:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: IsometricCityHostApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.isocity.host
        PRODUCT_NAME: IsometricCityHost
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_CFBundleDisplayName: IsoCity Host
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_NSAppTransportSecurity_NSAllowsArbitraryLoads: true
        INFOPLIST_KEY_UIRequiresFullScreen: false
